/**
 * Generates the Poseidon libraries in core/contracts/src from src/poseidon-constants.json:
 * PoseidonT3.sol (hash2), PoseidonT4.sol (hash3) and PoseidonBN254.sol, a facade over the two.
 *
 *   node tools/poseidon-sol.ts && (cd core/contracts && forge fmt src/Poseidon*.sol)
 *
 * The pinned files match only after forge fmt. The constants are the ones the circuit uses
 * (exported from circomlibjs by export-vectors.ts), and the loop-based Yul core implements
 * poseidon_reference.js's naive algorithm: state = [0, in...]; per round, add the round
 * constants (streamed from a bytes blob), apply the x^5 S-box (to every lane in the 4 initial
 * and 4 terminal rounds, to lane 0 otherwise), then new_state[i] = sum_j M[i][j] * state[j]
 * with the small matrix inlined; output state[0].
 *
 * Each half is its own library so its runtime fits the hegota devnet's 2^24 per-tx gas cap
 * (code deposit costs ~1545 gas/byte there under EIP-8037). The files still say they were
 * generated by split_poseidon.py, and must: the activation manifest and the formal SPEC.md pin
 * them, and the comment reaches the metadata hash of the deployed code.
 */
import { writeFileSync } from "node:fs";

import { readText } from "./check.ts";

const constants = JSON.parse(readText(new URL("../src/poseidon-constants.json", import.meta.url)));
const P = BigInt(constants.prime);

// The modulus lives in scratch memory (0x00), not a stack local: a local overflows legacy
// codegen's stack in hash3, and via-IR emits ~3KB of dispatch glue, both of which push
// PoseidonT4 past the deploy budget. Writing scratch space is allowed in memory-safe
// assembly; `bytes memory c = C4` allocates at the free pointer, so 0x00 is free. An
// mload(0x00) costs 6 gas to PUSH32's 3, but each avoided literal saves 30 bytes of runtime,
// which the devnet deploy budget values at ~1545 gas/byte.
const MODULUS = "mload(0x00)";

/** item(0) to item(count - 1), joined by sep. */
const each = (count: number, item: (i: number) => string, sep = "\n") =>
  Array.from({ length: count }, (_, i) => item(i)).join(sep);

/** The constants as Solidity hex"..." literal lines, three 32-byte big-endian words a line. */
function hexLines(values: string[]): string {
  const words = values.map((x) => {
    const word = BigInt(x);
    if (word < 0n || word >> 256n !== 0n) throw new RangeError(`constant ${x} exceeds 32 bytes`);
    return word.toString(16).padStart(64, "0");
  });
  const lines = [];
  for (let i = 0; i < words.length; i += 3) {
    lines.push(`        hex"${words.slice(i, i + 3).join("")}"`);
  }
  return lines.join("\n");
}

/**
 * Yul for new_state = M * state with inlined matrix literals.
 *
 * Lazy reduction: each term mulmod-reduces its (possibly unreduced) input, so the row sum of
 * t terms < t*P fits a word without addmod ((t+1)*P must stay < 2^256, which holds for t = 3
 * and t = 4 over BN254; a t = 5 blob would overflow and need the addmod form back).
 */
function mix(t: number, M: string[][], pad: string): string {
  const row = (i: number) => {
    const terms = M[i].slice(0, t).map((m, j) => `mulmod(${BigInt(m)}, s${j}, ${MODULUS})`);
    // Left-nested: add(add(term0, term1), term2).
    return terms.slice(1).reduce((sum, term) => `add(${sum}, ${term})`, terms[0]);
  };
  return each(t, (i) => `${pad}n${i} := ${row(i)}`) + "\n" + each(t, (i) => `${pad}s${i} := n${i}`);
}

/**
 * Inline x^5 for one lane, using n0 (dead until the mix rewrites it) as the x^2 scratch: a
 * fresh local would be one stack slot too many for legacy codegen in hash3 (the devnet
 * libsmall profile), and a Yul function call costs ~25 gas per invocation. Reduces the lane
 * mod P as a side effect, which the lazy-reduction invariant uses.
 */
function sbox(i: number, pad: string): string {
  return (
    `${pad}n0 := mulmod(s${i}, s${i}, ${MODULUS})\n` +
    `${pad}s${i} := mulmod(mulmod(n0, n0, ${MODULUS}), s${i}, ${MODULUS})`
  );
}

/** The library for t = nInputs + 1: its round constants and its hashN function. */
function library(t: number): string {
  const cfg = constants[`t${t}`];
  const [rf, rp] = [Number(cfg.rounds_f), Number(cfg.rounds_p)];
  const half = Math.floor(rf / 2);
  const n = t - 1;
  const name = `PoseidonT${t}`;
  return `// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.24;

/// @title ${name} — circomlib Poseidon t=${t} half of PoseidonBN254
/// @notice Split out of PoseidonBN254.sol so each half's runtime fits the
///         hegota devnet's 2^24 per-tx gas cap (EIP-8037 code deposit is
///         ~1545 gas/byte there; the combined library needs ~30M to deploy).
///         Same constants, same rounds, same output; the field-modulus
///         literal is hoisted into scratch memory (slot 0x00) to shrink
///         code size. Verified by the differential vectors in
///         ../test/PoseidonVectors.t.sol.
/// @dev    GENERATED by split_poseidon.py from PoseidonBN254.sol.
library ${name} {
    /// ${cfg.C.length} t=${t} round constants, 32 bytes each, big-endian.
    bytes internal constant C${t} =
${hexLines(cfg.C)};

    /// @notice circomlib Poseidon(${n}): state [0, inputs...], output state[0].
    /// @dev    public, so the library deploys once and the pool stays under
    ///         the EIP-170 code-size limit (via-IR inlines internal copies).
    ///         Lazily reduced: between the entry mod and the s-boxes, state
    ///         words carry values up to t*P and only mulmod reduces; the ark
    ///         and mix use plain add (sums bounded by (t+1)*P < 2^256, which
    ///         holds for t <= 4 over BN254), and the output takes one final
    ///         mod. Lane 0 passes the s-box every round; lanes 1..${n} only in
    ///         the ${half} initial and ${rf - half} terminal full rounds.
    function hash${n}(${each(n, (i) => `uint256 x${i}`, ", ")}) public pure returns (uint256 out) {
        bytes memory c = C${t};
        assembly ("memory-safe") {
            mstore(0x00, ${P})
            let cp := add(c, 32)
            let s0 := 0
${each(n, (i) => `            let s${i + 1} := mod(x${i}, ${MODULUS})`)}
            ${each(t, (i) => `let n${i} := 0`, " ")}
            for { let r := 0 } lt(r, ${rf + rp}) { r := add(r, 1) } {
${each(t, (i) => `                s${i} := add(s${i}, mload(add(cp, ${32 * i})))`)}
                cp := add(cp, ${32 * t})
${sbox(0, " ".repeat(16))}
                if or(lt(r, ${half}), gt(r, ${half + rp - 1})) {
${each(t - 1, (i) => sbox(i + 1, " ".repeat(20)))}
                }
${mix(t, cfg.M, " ".repeat(16))}
            }
            s0 := mod(s0, ${MODULUS})
            out := s0
        }
    }
}
`;
}

const FACADE = `// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.24;

import {PoseidonT3} from "./PoseidonT3.sol";
import {PoseidonT4} from "./PoseidonT4.sol";

/// @title PoseidonBN254 — circomlib's Poseidon, on-chain
/// @notice Facade over PoseidonT3/PoseidonT4 (see those files for the round
///         function). Split so each half deploys under the hegota devnet's
///         2^24 per-tx gas cap; callers and the differential vector tests are
///         unchanged. Inline wrappers compile to one DELEGATECALL per hash,
///         exactly as the pre-split public library did.
library PoseidonBN254 {
    uint256 internal constant P = ${P};

    function hash2(uint256 x0, uint256 x1) internal pure returns (uint256) {
        return PoseidonT3.hash2(x0, x1);
    }

    function hash3(uint256 x0, uint256 x1, uint256 x2) internal pure returns (uint256) {
        return PoseidonT4.hash3(x0, x1, x2);
    }
}
`;

if (import.meta.main) {
  const files = {
    "PoseidonT3.sol": library(3),
    "PoseidonT4.sol": library(4),
    "PoseidonBN254.sol": FACADE,
  };
  for (const [name, text] of Object.entries(files)) {
    writeFileSync(new URL(`../core/contracts/src/${name}`, import.meta.url), text);
  }
  console.log("wrote src/PoseidonT3.sol src/PoseidonT4.sol; rewrote src/PoseidonBN254.sol");
}
