"""Generates ../src/Poseidon16.sol from round_constants.json.

The permutation core is Yul with the state at raw memory pointers and the
circulant MDS fully unrolled (12 muls + 15 adds + 1 mod per output lane;
coefficient-1 terms skip the mul). Regenerate after any constant change:

    python3 gen_poseidon_sol.py && (cd .. && forge test)

The generated file is committed; this script is the source of truth for it.
"""
import json
from pathlib import Path

HERE = Path(__file__).parent
P = 2**31 - 2**24 + 1
COL = [1, 3, 13, 22, 67, 2, 15, 63, 101, 1, 2, 17, 11, 1, 51, 1]
RC = json.loads((HERE / "round_constants.json").read_text())
assert len(RC) == 28 and all(len(r) == 16 for r in RC)

rc_blob = b"".join(int(c).to_bytes(4, "big") for row in RC for c in row)
rc_lines = "\n".join(f'        hex"{rc_blob.hex()[i:i+96]}"'
                     for i in range(0, len(rc_blob.hex()), 96))

# addrc: two 32-byte words hold the round's 16 big-endian u32 constants
addrc = []
for lane in range(16):
    word = "w0" if lane < 8 else "w1"
    sh = 224 - 32 * (lane % 8)
    if sh == 224:
        ex = f"shr(224, {word})"
    elif sh == 0:
        ex = f"and({word}, 0xffffffff)"
    else:
        ex = f"and(shr({sh}, {word}), 0xffffffff)"
    off = f"add(sp, {32 * lane})" if lane else "sp"
    addrc.append(f"                mstore({off}, add(mload({off}), {ex}))")
addrc_body = "\n".join(addrc)

# mds: t[i] = sum_j COL[(i - j) mod 16] * s[j], unrolled
loads = "\n".join(
    f"                let s{j} := mload({f'add(sp, {32 * j})' if j else 'sp'})"
    for j in range(16))
rows = []
for i in range(16):
    terms = []
    for j in range(16):
        c = COL[(i - j) % 16]
        terms.append(f"s{j}" if c == 1 else f"mul({c}, s{j})")
    acc = terms[0]
    for t in terms[1:]:
        acc = f"add({acc}, {t})"
    off = f"add(tp, {32 * i})" if i else "tp"
    rows.append(f"                mstore({off}, mod({acc}, {P}))")
mds_body = "\n".join(rows)

sbox16 = "\n".join(
    "                {off_let}\n"
    "                mstore({off}, mulmod(mulmod(x{i}, x{i}, {p}), x{i}, {p}))".format(
        off_let=f"let x{i} := mload({f'add(sp, {32 * i})' if i else 'sp'})",
        off=f"add(sp, {32 * i})" if i else "sp", i=i, p=P)
    for i in range(16))

SOL = f'''// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.24;

/// @title Poseidon16 — leanVM's hash, on-chain
/// @notice Classic Poseidon (not Poseidon2) over KoalaBear (p = 2^31 - 2^24 + 1),
///         width 16, x^3 S-box, 4 initial + 20 partial + 4 terminal rounds,
///         circulant MDS M[i][j] = COL[(i - j) mod 16] with
///         COL = {COL}, and
///         compress(x) = (permute(x) + x)[0..8]. Constants transcribed from
///         leanVM commit 12e6151 (Poseidon1KoalaBear16); differentially tested
///         against vectors exported from that exact commit, see
///         test/Poseidon16Vectors.t.sol and ../reference/poseidon16.py.
/// @dev    GENERATED by reference/gen_poseidon_sol.py — edit that, not this.
///         The Yul core keeps the state at raw memory pointers with the MDS
///         unrolled; additions are lazily reduced (products stay below 2^44).
library Poseidon16 {{
    uint256 internal constant P = {P}; // 2^31 - 2^24 + 1

    /// 28 rounds x 16 round constants, 4 bytes each, big-endian (canonical).
    bytes internal constant RC =
{rc_lines};

    /// @notice The Poseidon16 permutation. Clobbers `s`; the result may alias
    ///         either internal buffer, so use the returned array.
    function permute(uint256[16] memory s) internal pure returns (uint256[16] memory out) {{
        bytes memory rc = RC;
        uint256[16] memory t;
        assembly ("memory-safe") {{
            function addrc(sp, rcp) {{
                let w0 := mload(rcp)
                let w1 := mload(add(rcp, 32))
{addrc_body}
            }}
            function sbox16(sp) {{
{sbox16}
            }}
            function sbox1(sp) {{
                let x := mload(sp)
                mstore(sp, mulmod(mulmod(x, x, {P}), x, {P}))
            }}
            function mds(sp, tp) {{
{loads}
{mds_body}
            }}
            let a := s
            let b := t
            let rcp := add(rc, 32)
            for {{ let r := 0 }} lt(r, 28) {{ r := add(r, 1) }} {{
                addrc(a, rcp)
                rcp := add(rcp, 64)
                switch or(lt(r, 4), gt(r, 23))
                case 1 {{ sbox16(a) }}
                default {{ sbox1(a) }}
                mds(a, b)
                let tmp := a
                a := b
                b := tmp
            }}
            out := a
        }}
    }}

    /// @notice 16 -> 8 compression: permute, feed the input forward, truncate.
    function compress(uint256[16] memory x) internal pure returns (uint256[8] memory out) {{
        uint256[8] memory ff;
        for (uint256 i = 0; i < 8; i++) ff[i] = x[i];
        uint256[16] memory y = permute(x);
        unchecked {{
            for (uint256 i = 0; i < 8; i++) out[i] = (y[i] + ff[i]) % P;
        }}
    }}

    /// @notice compress(a || b), the Merkle/tagged-hash two-to-one primitive.
    function compressPair(uint256[8] memory a, uint256[8] memory b)
        internal pure returns (uint256[8] memory)
    {{
        uint256[16] memory x;
        for (uint256 i = 0; i < 8; i++) {{ x[i] = a[i]; x[8 + i] = b[i]; }}
        return compress(x);
    }}

    /// @notice The pool's domain-separated hash: compress(tag_block, compress(a, b)).
    function tagged(uint256 tag, uint256[8] memory a, uint256[8] memory b)
        internal pure returns (uint256[8] memory)
    {{
        uint256[8] memory tb;
        tb[0] = tag;
        return compressPair(tb, compressPair(a, b));
    }}

    /// @notice Canonical digest encoding: 8 big-endian 32-bit words in one bytes32.
    ///         This value is the uint256 nonce key for nf, the bytes32 root, and
    ///         the byte string hashed on claim recompute (see devnet/README.md).
    function packDigest(uint256[8] memory d) internal pure returns (bytes32) {{
        uint256 acc;
        unchecked {{
            for (uint256 i = 0; i < 8; i++) {{
                require(d[i] < P, "not a field element");
                acc = (acc << 32) | d[i];
            }}
        }}
        return bytes32(acc);
    }}

    /// @notice Inverse of packDigest; rejects non-canonical encodings.
    function unpackDigest(bytes32 b) internal pure returns (uint256[8] memory d) {{
        uint256 acc = uint256(b);
        unchecked {{
            for (uint256 i = 0; i < 8; i++) {{
                uint256 w = (acc >> (32 * (7 - i))) & 0xffffffff;
                require(w < P, "not a canonical digest");
                d[i] = w;
            }}
        }}
    }}
}}
'''

(HERE.parent / "src" / "Poseidon16.sol").write_text(SOL)
print("src/Poseidon16.sol generated")
