// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.24;

/// @title Poseidon16 — leanVM's hash, on-chain
/// @notice Classic Poseidon (not Poseidon2) over KoalaBear (p = 2^31 - 2^24 + 1),
///         width 16, x^3 S-box, 4 initial + 20 partial + 4 terminal rounds,
///         circulant MDS M[i][j] = COL[(i - j) mod 16] with
///         COL = [1, 3, 13, 22, 67, 2, 15, 63, 101, 1, 2, 17, 11, 1, 51, 1], and
///         compress(x) = (permute(x) + x)[0..8]. Constants transcribed from
///         leanVM commit 12e6151 (Poseidon1KoalaBear16); differentially tested
///         against vectors exported from that exact commit, see
///         test/Poseidon16Vectors.t.sol and ../reference/poseidon16.py.
/// @dev    GENERATED by reference/gen_poseidon_sol.py — edit that, not this.
///         The Yul core keeps the state at raw memory pointers with the MDS
///         unrolled; additions are lazily reduced (products stay below 2^44).
library Poseidon16 {
    uint256 internal constant P = 2130706433; // 2^31 - 2^24 + 1

    /// 28 rounds x 16 round constants, 4 bytes each, big-endian (canonical).
    bytes internal constant RC =
        hex"7ee56a481136704512e419417ebbc12b1970b7d5662b60e83e4990c6679f91f5350813bb00874ad428a0081a18fa5872"
        hex"5f25b0715e5d59985e6fd3e75b2e26606f1837bf3fe6182b1edd7ac557470d0043d486d51982c70f0ea53af961d6165b"
        hex"51639c002dec352c2950e5312d2cb94708256cef1a0109f61f51faf35cef1c623d65e50e33d91626133d5a1e0ff49b0d"
        hex"38900cd12c22cc3f28852bb206c65a027b2cf7bc68016e1a15e16bc05248149a6dd212a018d6830a5001be8264dac34e"
        hex"5902b287426583a00c9216323fe028a5245f8e4943bb297e7873dbd93cc987df286bb4ce640a8dcd512a8e3603a4cf55"
        hex"481837a203d6da8473726ac7760e7fdf54dfeb5d7d40afd6722cb316106a457345a7ccdb44061375154077a545744faa"
        hex"4eb5e5ee3794e83f47c7093c5694903c69cb6299373df84c46a0df5846b8758a3241ebcb0b09d2331af423571e66cec2"
        hex"43e7dc24259a5d6127e85a3b1b9133fa343e5628485cd4c216e269f5165b60c625f683d9124f81f9174331f977344dc5"
        hex"5a821dba5fc4177f54153bf55e3f11943bdbf191088c84a368256c9b3c90bbc66846166a03f4238d463335fb5e3d3551"
        hex"6e59ae6f32d06cc0596293f36c87edb208fc60b534bcca8024f007f362731c6f1e1db6c60ca409bb585c1e7856e94edc"
        hex"16d2273418e114677b2c3730770075e435d1b18c22be3db54fb1fbb7477cb3ed7d5311c65b62ae7d559c5fa877f15048"
        hex"3211570b490fef6a77ec311f2247171b4e0ac7112edf69c93b5a8850658094215619b4aa362019a76bf9d4ed5b413dff"
        hex"617e181e5e7ab57b33ad78333466c7ca6488dff471f068f4056e891f04f1eccc663257d5671e31b95871987c280c109e"
        hex"2a227761350a25e95b91b1c47a0735460182627053a677200ed4b07434cf0c4e6e751e8829bd5f5949ec32df7693452b"
        hex"3cf09e586ba0e2bf7ab93acf3ce597df536e3d42147a808d5e32eb565a203323509657666d44b7c56698636a57b84f9f"
        hex"554b61b96da0ab281585b6ac6705a2b4152872f60f4409fd23a9dd606f2b18d465ac9fd42f0efbea591e67fd217ca19b"
        hex"469c90ca03d60ef54ea7857e07c86a4f288ed4612fe51b227e2936142c4beb855b0b7d111e17dff6089beae10a5acf1a"
        hex"2fc33d8f60422dc66e1dc939635351b955522fc03eb94ef72a24a65c2e139c765139114478cc0742579538f944de9aae"
        hex"3c2f1e2e195747be2496339c650b2e39528996656cb355580f461c1c70f6b2703faaa36f62e3348a672167cb394c880b"
        hex"2a46ba8263ffb74a1cf875d653d12772036a45523bdd9f2b02f72c2402b6006c077fe1581f9d6ea420904d6f5d6534fa"
        hex"066d89746198f1f426301ab441f274c200eac15c28b54b472339739d48c6281c4ed935fc3f9187fa4a1930a63ad4d736"
        hex"0f3f1889635a388f2862c145277ed1e84db23cad1f1b11f51f3dba2b1c26eb4e0f7f55466cd024b067c47902793b8900"
        hex"0e8a283c4590b7ea6f567a2b5dc9730015247bc650567fcb133eff84547dc2ef34eb3dbb1240231766c6ae49174338b6"
        hex"242510081b514927062d98d67af30bbc26af15e870d907a35dfc5cac731f27ec53aa7d3f63ab0ec6216053f418796b39"
        hex"19156afd5eea69736704c6a90dce002b331169c0714d71783ddaffaf7e46495720ca59ea679820c942ef21a1798ea089"
        hex"14a74fa30c06cf186a4c8d52620f6d812220901a5277bb90230bf95e0ad8847a5e96e8b677b4056e70a50d2c5f0eed59"
        hex"3646c4df10eb9a8721eed6b7534add366e3e74212b25810e1d8f707b45318a1a677f8ff20258c9e04cd02a002e24ff15"
        hex"634a715d4ac01e59601511e126e9c01a4c165c6e57cd11403ac6543b6787d847037dfbf96dd9d0794d24b2812a6f407d"
        hex"0131df8e4b8a7896237008582cf5e53412aafc3f54568d031a2507355331686d4ce76d91799c1a8c2b7a8ac960aee672"
        hex"74f7421c3c42146d26d369c54ae54a127eea16d15ce3eae869f28994262b8642610d4cc45e1af21c1a8526d0316b127b"
        hex"3576fe5d02d968a04ba00f5140bed993377fb9077859216e1931d9d153b0934e71914ff74eabae6c7196468e164b3cc2"
        hex"58cb66c04c1473076b3afccd4236518b4ad85605291382e11e89b6cf5e16c3a82e6759212430095405e555c378880a24"
        hex"763a31254f53b24018b7fa432bbe8a731c9a12f23f6fd40d0e1d4ec41361c64d09a8f47003d23a40109ad29028c2fb88"
        hex"3b6498f274d8be576a4277d218c2b3d46252c30c07cc2560209fe15b52a55fac4df19eb7025211165e414ff13cd9a1f4"
        hex"005aad1527a53f0072bbe9cb71d8bd7d4194b79a48e87a723341553c63d34faa132a01e33833e2d949726e04054957f8"
        hex"7b71bce473eec57d556e55331fa93fde346a8ca81162dfde5c30d028094a42943052dcda3798849851f06b9765848779"
        hex"7599b0d4436fdabc66c5b77d40c86a9e27e7055b6d0dd9d87e5598b51a4d04f35e3b2bc7533b5b2f3e33a125664d71ce"
        hex"382e6c2a24c4eb6e13f246f707e2d7ef";

    /// @notice The Poseidon16 permutation. Clobbers `s`; the result may alias
    ///         either internal buffer, so use the returned array.
    function permute(uint256[16] memory s) internal pure returns (uint256[16] memory out) {
        bytes memory rc = RC;
        uint256[16] memory t;
        assembly ("memory-safe") {
            function addrc(sp, rcp) {
                let w0 := mload(rcp)
                let w1 := mload(add(rcp, 32))
                mstore(sp, add(mload(sp), shr(224, w0)))
                mstore(add(sp, 32), add(mload(add(sp, 32)), and(shr(192, w0), 0xffffffff)))
                mstore(add(sp, 64), add(mload(add(sp, 64)), and(shr(160, w0), 0xffffffff)))
                mstore(add(sp, 96), add(mload(add(sp, 96)), and(shr(128, w0), 0xffffffff)))
                mstore(add(sp, 128), add(mload(add(sp, 128)), and(shr(96, w0), 0xffffffff)))
                mstore(add(sp, 160), add(mload(add(sp, 160)), and(shr(64, w0), 0xffffffff)))
                mstore(add(sp, 192), add(mload(add(sp, 192)), and(shr(32, w0), 0xffffffff)))
                mstore(add(sp, 224), add(mload(add(sp, 224)), and(w0, 0xffffffff)))
                mstore(add(sp, 256), add(mload(add(sp, 256)), shr(224, w1)))
                mstore(add(sp, 288), add(mload(add(sp, 288)), and(shr(192, w1), 0xffffffff)))
                mstore(add(sp, 320), add(mload(add(sp, 320)), and(shr(160, w1), 0xffffffff)))
                mstore(add(sp, 352), add(mload(add(sp, 352)), and(shr(128, w1), 0xffffffff)))
                mstore(add(sp, 384), add(mload(add(sp, 384)), and(shr(96, w1), 0xffffffff)))
                mstore(add(sp, 416), add(mload(add(sp, 416)), and(shr(64, w1), 0xffffffff)))
                mstore(add(sp, 448), add(mload(add(sp, 448)), and(shr(32, w1), 0xffffffff)))
                mstore(add(sp, 480), add(mload(add(sp, 480)), and(w1, 0xffffffff)))
            }
            function sbox16(sp) {
                let x0 := mload(sp)
                mstore(sp, mulmod(mulmod(x0, x0, 2130706433), x0, 2130706433))
                let x1 := mload(add(sp, 32))
                mstore(add(sp, 32), mulmod(mulmod(x1, x1, 2130706433), x1, 2130706433))
                let x2 := mload(add(sp, 64))
                mstore(add(sp, 64), mulmod(mulmod(x2, x2, 2130706433), x2, 2130706433))
                let x3 := mload(add(sp, 96))
                mstore(add(sp, 96), mulmod(mulmod(x3, x3, 2130706433), x3, 2130706433))
                let x4 := mload(add(sp, 128))
                mstore(add(sp, 128), mulmod(mulmod(x4, x4, 2130706433), x4, 2130706433))
                let x5 := mload(add(sp, 160))
                mstore(add(sp, 160), mulmod(mulmod(x5, x5, 2130706433), x5, 2130706433))
                let x6 := mload(add(sp, 192))
                mstore(add(sp, 192), mulmod(mulmod(x6, x6, 2130706433), x6, 2130706433))
                let x7 := mload(add(sp, 224))
                mstore(add(sp, 224), mulmod(mulmod(x7, x7, 2130706433), x7, 2130706433))
                let x8 := mload(add(sp, 256))
                mstore(add(sp, 256), mulmod(mulmod(x8, x8, 2130706433), x8, 2130706433))
                let x9 := mload(add(sp, 288))
                mstore(add(sp, 288), mulmod(mulmod(x9, x9, 2130706433), x9, 2130706433))
                let x10 := mload(add(sp, 320))
                mstore(add(sp, 320), mulmod(mulmod(x10, x10, 2130706433), x10, 2130706433))
                let x11 := mload(add(sp, 352))
                mstore(add(sp, 352), mulmod(mulmod(x11, x11, 2130706433), x11, 2130706433))
                let x12 := mload(add(sp, 384))
                mstore(add(sp, 384), mulmod(mulmod(x12, x12, 2130706433), x12, 2130706433))
                let x13 := mload(add(sp, 416))
                mstore(add(sp, 416), mulmod(mulmod(x13, x13, 2130706433), x13, 2130706433))
                let x14 := mload(add(sp, 448))
                mstore(add(sp, 448), mulmod(mulmod(x14, x14, 2130706433), x14, 2130706433))
                let x15 := mload(add(sp, 480))
                mstore(add(sp, 480), mulmod(mulmod(x15, x15, 2130706433), x15, 2130706433))
            }
            function sbox1(sp) {
                let x := mload(sp)
                mstore(sp, mulmod(mulmod(x, x, 2130706433), x, 2130706433))
            }
            function mds(sp, tp) {
                let s0 := mload(sp)
                let s1 := mload(add(sp, 32))
                let s2 := mload(add(sp, 64))
                let s3 := mload(add(sp, 96))
                let s4 := mload(add(sp, 128))
                let s5 := mload(add(sp, 160))
                let s6 := mload(add(sp, 192))
                let s7 := mload(add(sp, 224))
                let s8 := mload(add(sp, 256))
                let s9 := mload(add(sp, 288))
                let s10 := mload(add(sp, 320))
                let s11 := mload(add(sp, 352))
                let s12 := mload(add(sp, 384))
                let s13 := mload(add(sp, 416))
                let s14 := mload(add(sp, 448))
                let s15 := mload(add(sp, 480))
                mstore(tp, mod(add(add(add(add(add(add(add(add(add(add(add(add(add(add(add(s0, s1), mul(51, s2)), s3), mul(11, s4)), mul(17, s5)), mul(2, s6)), s7), mul(101, s8)), mul(63, s9)), mul(15, s10)), mul(2, s11)), mul(67, s12)), mul(22, s13)), mul(13, s14)), mul(3, s15)), 2130706433))
                mstore(add(tp, 32), mod(add(add(add(add(add(add(add(add(add(add(add(add(add(add(add(mul(3, s0), s1), s2), mul(51, s3)), s4), mul(11, s5)), mul(17, s6)), mul(2, s7)), s8), mul(101, s9)), mul(63, s10)), mul(15, s11)), mul(2, s12)), mul(67, s13)), mul(22, s14)), mul(13, s15)), 2130706433))
                mstore(add(tp, 64), mod(add(add(add(add(add(add(add(add(add(add(add(add(add(add(add(mul(13, s0), mul(3, s1)), s2), s3), mul(51, s4)), s5), mul(11, s6)), mul(17, s7)), mul(2, s8)), s9), mul(101, s10)), mul(63, s11)), mul(15, s12)), mul(2, s13)), mul(67, s14)), mul(22, s15)), 2130706433))
                mstore(add(tp, 96), mod(add(add(add(add(add(add(add(add(add(add(add(add(add(add(add(mul(22, s0), mul(13, s1)), mul(3, s2)), s3), s4), mul(51, s5)), s6), mul(11, s7)), mul(17, s8)), mul(2, s9)), s10), mul(101, s11)), mul(63, s12)), mul(15, s13)), mul(2, s14)), mul(67, s15)), 2130706433))
                mstore(add(tp, 128), mod(add(add(add(add(add(add(add(add(add(add(add(add(add(add(add(mul(67, s0), mul(22, s1)), mul(13, s2)), mul(3, s3)), s4), s5), mul(51, s6)), s7), mul(11, s8)), mul(17, s9)), mul(2, s10)), s11), mul(101, s12)), mul(63, s13)), mul(15, s14)), mul(2, s15)), 2130706433))
                mstore(add(tp, 160), mod(add(add(add(add(add(add(add(add(add(add(add(add(add(add(add(mul(2, s0), mul(67, s1)), mul(22, s2)), mul(13, s3)), mul(3, s4)), s5), s6), mul(51, s7)), s8), mul(11, s9)), mul(17, s10)), mul(2, s11)), s12), mul(101, s13)), mul(63, s14)), mul(15, s15)), 2130706433))
                mstore(add(tp, 192), mod(add(add(add(add(add(add(add(add(add(add(add(add(add(add(add(mul(15, s0), mul(2, s1)), mul(67, s2)), mul(22, s3)), mul(13, s4)), mul(3, s5)), s6), s7), mul(51, s8)), s9), mul(11, s10)), mul(17, s11)), mul(2, s12)), s13), mul(101, s14)), mul(63, s15)), 2130706433))
                mstore(add(tp, 224), mod(add(add(add(add(add(add(add(add(add(add(add(add(add(add(add(mul(63, s0), mul(15, s1)), mul(2, s2)), mul(67, s3)), mul(22, s4)), mul(13, s5)), mul(3, s6)), s7), s8), mul(51, s9)), s10), mul(11, s11)), mul(17, s12)), mul(2, s13)), s14), mul(101, s15)), 2130706433))
                mstore(add(tp, 256), mod(add(add(add(add(add(add(add(add(add(add(add(add(add(add(add(mul(101, s0), mul(63, s1)), mul(15, s2)), mul(2, s3)), mul(67, s4)), mul(22, s5)), mul(13, s6)), mul(3, s7)), s8), s9), mul(51, s10)), s11), mul(11, s12)), mul(17, s13)), mul(2, s14)), s15), 2130706433))
                mstore(add(tp, 288), mod(add(add(add(add(add(add(add(add(add(add(add(add(add(add(add(s0, mul(101, s1)), mul(63, s2)), mul(15, s3)), mul(2, s4)), mul(67, s5)), mul(22, s6)), mul(13, s7)), mul(3, s8)), s9), s10), mul(51, s11)), s12), mul(11, s13)), mul(17, s14)), mul(2, s15)), 2130706433))
                mstore(add(tp, 320), mod(add(add(add(add(add(add(add(add(add(add(add(add(add(add(add(mul(2, s0), s1), mul(101, s2)), mul(63, s3)), mul(15, s4)), mul(2, s5)), mul(67, s6)), mul(22, s7)), mul(13, s8)), mul(3, s9)), s10), s11), mul(51, s12)), s13), mul(11, s14)), mul(17, s15)), 2130706433))
                mstore(add(tp, 352), mod(add(add(add(add(add(add(add(add(add(add(add(add(add(add(add(mul(17, s0), mul(2, s1)), s2), mul(101, s3)), mul(63, s4)), mul(15, s5)), mul(2, s6)), mul(67, s7)), mul(22, s8)), mul(13, s9)), mul(3, s10)), s11), s12), mul(51, s13)), s14), mul(11, s15)), 2130706433))
                mstore(add(tp, 384), mod(add(add(add(add(add(add(add(add(add(add(add(add(add(add(add(mul(11, s0), mul(17, s1)), mul(2, s2)), s3), mul(101, s4)), mul(63, s5)), mul(15, s6)), mul(2, s7)), mul(67, s8)), mul(22, s9)), mul(13, s10)), mul(3, s11)), s12), s13), mul(51, s14)), s15), 2130706433))
                mstore(add(tp, 416), mod(add(add(add(add(add(add(add(add(add(add(add(add(add(add(add(s0, mul(11, s1)), mul(17, s2)), mul(2, s3)), s4), mul(101, s5)), mul(63, s6)), mul(15, s7)), mul(2, s8)), mul(67, s9)), mul(22, s10)), mul(13, s11)), mul(3, s12)), s13), s14), mul(51, s15)), 2130706433))
                mstore(add(tp, 448), mod(add(add(add(add(add(add(add(add(add(add(add(add(add(add(add(mul(51, s0), s1), mul(11, s2)), mul(17, s3)), mul(2, s4)), s5), mul(101, s6)), mul(63, s7)), mul(15, s8)), mul(2, s9)), mul(67, s10)), mul(22, s11)), mul(13, s12)), mul(3, s13)), s14), s15), 2130706433))
                mstore(add(tp, 480), mod(add(add(add(add(add(add(add(add(add(add(add(add(add(add(add(s0, mul(51, s1)), s2), mul(11, s3)), mul(17, s4)), mul(2, s5)), s6), mul(101, s7)), mul(63, s8)), mul(15, s9)), mul(2, s10)), mul(67, s11)), mul(22, s12)), mul(13, s13)), mul(3, s14)), s15), 2130706433))
            }
            let a := s
            let b := t
            let rcp := add(rc, 32)
            for { let r := 0 } lt(r, 28) { r := add(r, 1) } {
                addrc(a, rcp)
                rcp := add(rcp, 64)
                switch or(lt(r, 4), gt(r, 23))
                case 1 { sbox16(a) }
                default { sbox1(a) }
                mds(a, b)
                let tmp := a
                a := b
                b := tmp
            }
            out := a
        }
    }

    /// @notice 16 -> 8 compression: permute, feed the input forward, truncate.
    function compress(uint256[16] memory x) internal pure returns (uint256[8] memory out) {
        uint256[8] memory ff;
        for (uint256 i = 0; i < 8; i++) ff[i] = x[i];
        uint256[16] memory y = permute(x);
        unchecked {
            for (uint256 i = 0; i < 8; i++) out[i] = (y[i] + ff[i]) % P;
        }
    }

    /// @notice compress(a || b), the Merkle/tagged-hash two-to-one primitive.
    function compressPair(uint256[8] memory a, uint256[8] memory b)
        internal pure returns (uint256[8] memory)
    {
        uint256[16] memory x;
        for (uint256 i = 0; i < 8; i++) { x[i] = a[i]; x[8 + i] = b[i]; }
        return compress(x);
    }

    /// @notice The pool's domain-separated hash: compress(tag_block, compress(a, b)).
    function tagged(uint256 tag, uint256[8] memory a, uint256[8] memory b)
        internal pure returns (uint256[8] memory)
    {
        uint256[8] memory tb;
        tb[0] = tag;
        return compressPair(tb, compressPair(a, b));
    }

    /// @notice Canonical digest encoding: 8 big-endian 32-bit words in one bytes32.
    ///         This value is the uint256 nonce key for nf, the bytes32 root, and
    ///         the byte string hashed on claim recompute (see devnet/README.md).
    function packDigest(uint256[8] memory d) internal pure returns (bytes32) {
        uint256 acc;
        unchecked {
            for (uint256 i = 0; i < 8; i++) {
                require(d[i] < P, "not a field element");
                acc = (acc << 32) | d[i];
            }
        }
        return bytes32(acc);
    }

    /// @notice Inverse of packDigest; rejects non-canonical encodings.
    function unpackDigest(bytes32 b) internal pure returns (uint256[8] memory d) {
        uint256 acc = uint256(b);
        unchecked {
            for (uint256 i = 0; i < 8; i++) {
                uint256 w = (acc >> (32 * (7 - i))) & 0xffffffff;
                require(w < P, "not a canonical digest");
                d[i] = w;
            }
        }
    }
}
